name: Update chart data

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        
    - name: Run data pull script
      env:
        GDOC_CREDENTIALS: ${{ secrets.GDOC_CREDENTIALS }}
      run: uv run pull_chart_data.py
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain data.json)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Set job output
      id: set-output
      run: echo "changed=${{ steps.verify-changed-files.outputs.changed }}" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      env:
        TZ: America/New_York
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Update chart data - $(date +"%Y-%m-%d %H:%M:%S %Z")"
        git push

    outputs:
      changed: ${{ steps.set-output.outputs.changed }}
  trigger-build:
    needs: update-data
    if: needs.update-data.outputs.changed == 'true'
    uses: ./.github/workflows/build-and-deploy.yaml